"""add question metadata columns

Revision ID: 68884fc0d405
Revises: dbc9c57b2e19
Create Date: 2026-01-03 15:11:28.712949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68884fc0d405'
down_revision: Union[str, Sequence[str], None] = 'dbc9c57b2e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('topic', sa.String(length=150), nullable=True))
    op.add_column('questions', sa.Column('subtopic', sa.String(length=200), nullable=True))
    op.add_column('questions', sa.Column('exam_name', sa.String(length=120), nullable=True))
    op.add_column('questions', sa.Column('question_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_number')
    op.drop_column('questions', 'exam_name')
    op.drop_column('questions', 'subtopic')
    op.drop_column('questions', 'topic')
    # ### end Alembic commands ###
